### Get all blogs
GET http://localhost:3001/api/blogs

### Post a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test Blog",
  "author": "Test Author",
  "url": "http://example.com",
  "likes": 0,
  "user": {
    "name": "Nick",
    "username": "nick"
  }
}
